#
# Unscripted Build Configuration
# Unscripted Core
#
# Created by Marquis Kurt on 04/16/20.
# Copyright © 2020 Marquis Kurt. All rights reserved.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

# Feature Configuration
# The following settings control the different features in the game.
[config.features]

# Whether we want to enable to 'Dreams' functionality of the game. Dreams are small mods that are
# designed to be playable with a default Unscripted configuration.
enable_dreams = false

# Whether we want to enable the Advanced Mode option for the minigame.
enable_minigame_adv_mode = true

# The build channel for this release. Should be either "stable", "beta", or another string value.
channel = "stable"

# Labs Configuration
# The following settings control the experimental features for the current build.
[config.labs]

# The current list of experiments.
current = []

# Analytics Configuration
# The following settings control the bug reporting and (possible) analytics collection.
[config.analytics]

# Whether we want to enable the 'Report a Bug' link in the game menu.
enable_bug_reports = true

# The links to navigate to when clicking "Report a Bug".
# Can also be written as links = {stable = "", beta = ""}
[config.analytics.links]
stable = "https://1n.pm/AsuXE"
beta = "https://1n.pm/5twP3"

# If this option is included, the game will prompt the player to fill out a feedback form.
# To not prompt feedback, disable this line.
# survey_link = ""

# Discord Configuration
# The following settings control the Discord rich presence functionality.
[config.discord]

# Whether we want to enable Discord rich presence.
enable_rpc = true

# The Client ID from the Discord application in Discord Developers portal.
client_id = "000000000000000000"

# Demo Configuration
# The following settings control the demo build of the game.
[config.demo]

# Whether the version we are building is the demo version of the game.
demo = false

# The maximum number of days to play through, starting from zero (total count - 1). For example,
# for the first three days, the demo_max_count would be two.
demo_max_count = 2

# Whether we want to include the Unscripted Core source code with the game in the demo mode.
demo_bundle_core = false