[game.dictionary]
ayu = "A cool color scheme"
agile = "A methodology for developing software that focuses on releasing updates continously and responding to change."
bughorse = "What more do you want?"
