[level.config]
name = "An Unusual Office"
allowed_blocks = ["move", "collect", "exit"]
check = ["player-at-exit", "player-collects-all"]

[level.map]
layout = """
%%%%%%%%%%
%.      P%
% %%%%%%%%
% %.   %E%
%.  %%   %
%%%%%%%%%%
"""
