[level.config]
name = "Around the Bend"
allowed_blocks = ["move", "collect", "exit"]
check = ["player-powers-all-devices", "player-at-exit"]

[level.map]
layout = """
%%%%%%%
%P   .%
%%%%% %
%E   .%
%%%%%%%
"""
