[level.config]
name = "Symmetric"
allowed_blocks = ["move", "collect", "exit"]
check = ["player-powers-all-devices", "player-at-exit"]

[level.map]
layout = """
%%%%%%%
%.%E%.%
%     %
%.%P%.%
%%%%%%%
"""
