[level.config]
name = "Longer Corridors"
allowed_blocks = ["move", "collect", "define", "exit"]
check = ["player-powers-all-devices", "player-at-exit"]

[level.map]
layout = """
%%%%%%%%%
%P% . %E%
% % % % %
% % % % %
% . % . %
%%%%%%%%%
"""
