name: CI
on:
  push:
    paths:
      - "**/**.rpy"
      - "build.toml"
      - "requirements.txt"
      - ".github/workflows/lint.yml"

jobs:
  lint:
    name: Lint Project with SDK
    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Clone Candella source
        uses: actions/checkout@v2
        with:
          repository: 'UnscriptedVN/candella'
          path: 'candella'
      - name: Update Candella release
        run: |
          cd candella
          python3 ./scripts/version_inject.py
          cd ..
      - name: Build Candella release
        id: candella
        uses: ProjectAliceDev/renpy-build-action@v1.1.3
        with:
          sdk-version: 7.4.2
          project-dir: 'candella'
      - name: Add Candella build to release
        run: |
          cd ${{ steps.candella.outputs.dir }}
          unzip ${{ steps.candella.outputs.version }}-System.zip
          cp ./${{ steps.candella.outputs.version }}-System/game/candella.rpa ../game/game/
          cd ..
      - name: Lint project
        uses: ProjectAliceDev/renpy-lint-action@v1.1.1
        with:
          sdk-version: 7.4.1
          project-dir: "."
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy
          LANG: en_US.UTF-8
